# Generated by Django 5.2.8 on 2025-11-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='bot_text',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='user_sender',
        ),
        migrations.AddField(
            model_name='message',
            name='user_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
