# Generated by Django 5.2.8 on 2025-11-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_rename_text_message_bot_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='bot_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
